name: Deploy

on:
  release:
    types: [published]

jobs:
  test_lint_deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...
    - name: Deploy
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go
        zip main.zip main
        aws lambda update-function-code --function-name=totoprizecheck --zip-file=fileb://main.zip --no-publish
        aws lambda publish-version --function-name=totoprizecheck --description "${{ github.event.release.body }}"
      if: github.event.pull_request.merged
